### ISSUE TITLE
Duplicated image and self-cleaning

### ISSUE THREAD

**Issue by nibreh** [electricgecko/MARK#30]
Very nice and great app, thanks to you !

I got this error for duplicated images (after click on the same image)

`PHP Warning:  unlink() expects parameter 1 to be a valid path, array given in index.php on line 158`

In fact, the duplicated image is not deleted from server.

Not very important, but I wanted to tell you.

Cheers

**Comment by electricgecko** [comment]
hey there,
thanks for your kind words and for reporting this! 

turns out i was handing over the image array to unlink(), instead of processing the image itself and its thumbnail separately. fixed it with my latest commit: a2e583cf802390e0b0951fc0985cef09138e9f04

thanks for giving this a spin. let me know if you encounter anything else.

best,
malte
